"""
Signal models for the scoring engine.

Defines the TradeSignal dataclass, SignalType enum, and Confidence enum
used throughout the scoring and execution pipeline.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional


class SignalType(Enum):
    """Types of trading signals generated by the decision engine."""

    HIGH_PROBABILITY_LONG = "HIGH_PROBABILITY_LONG"
    EARLY_ACCUMULATION_WATCH = "EARLY_ACCUMULATION_WATCH"
    HIGH_RISK_DUMP_SHORT = "HIGH_RISK_DUMP_SHORT"
    NO_TRADE = "NO_TRADE"


class Confidence(Enum):
    """Confidence level for a trading signal."""

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


@dataclass
class TradeSignal:
    """Complete trading signal output from the decision engine.

    Contains the signal type, scoring metrics, confidence level,
    reasoning, and suggested trade parameters.
    """

    symbol: str
    signal_type: SignalType
    pump_score: float
    dump_score: float
    confidence: Confidence
    reasons: List[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)
    entry_price: Optional[float] = None
    suggested_stop_loss: Optional[float] = None
    suggested_take_profit: Optional[float] = None

    def to_dict(self) -> dict:
        """Convert to dictionary representation."""
        return {
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "pump_score": self.pump_score,
            "dump_score": self.dump_score,
            "confidence": self.confidence.value,
            "reasons": self.reasons,
            "timestamp": self.timestamp,
            "entry_price": self.entry_price,
            "suggested_stop_loss": self.suggested_stop_loss,
            "suggested_take_profit": self.suggested_take_profit,
        }
